services:
  - type: web
    name: yoohubdeobfbyfox
    runtime: node
    plan: free
    buildCommand: npm install && node scripts/fetch-luau-linux.js
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
